// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Config struct {
	Key   string
	Value string
}

type Subscription struct {
	ID              int64
	Name            string
	Amount          float64
	Currency        string
	BillingCycle    string
	NextRenewalDate sql.NullString
	CreatedAt       string
	UpdatedAt       string
}
