// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (name, amount, currency, billing_cycle, next_renewal_date)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, amount, currency, billing_cycle, next_renewal_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	Name            string
	Amount          float64
	Currency        string
	BillingCycle    string
	NextRenewalDate sql.NullString
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.BillingCycle,
		arg.NextRenewalDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.BillingCycle,
		&i.NextRenewalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE id = ?
`

func (q *Queries) DeleteSubscription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, id)
	return err
}

const getAllConfig = `-- name: GetAllConfig :many
SELECT key, value FROM config ORDER BY key
`

func (q *Queries) GetAllConfig(ctx context.Context) ([]Config, error) {
	rows, err := q.db.QueryContext(ctx, getAllConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSubscriptionsForExport = `-- name: GetAllSubscriptionsForExport :many
SELECT id, name, amount, currency, billing_cycle, next_renewal_date, created_at, updated_at
FROM subscriptions
ORDER BY name ASC
`

func (q *Queries) GetAllSubscriptionsForExport(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getAllSubscriptionsForExport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.BillingCycle,
			&i.NextRenewalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfig = `-- name: GetConfig :one
SELECT value FROM config WHERE key = ?
`

// Config queries
func (q *Queries) GetConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, name, amount, currency, billing_cycle, next_renewal_date, created_at, updated_at FROM subscriptions WHERE id = ?
`

func (q *Queries) GetSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.BillingCycle,
		&i.NextRenewalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getYearlySubscriptionsRenewingInMonth = `-- name: GetYearlySubscriptionsRenewingInMonth :many
SELECT id, name, amount, currency, billing_cycle, next_renewal_date, created_at, updated_at FROM subscriptions
WHERE billing_cycle = 'yearly' AND strftime('%Y-%m', next_renewal_date) = ?
ORDER BY next_renewal_date ASC
`

func (q *Queries) GetYearlySubscriptionsRenewingInMonth(ctx context.Context, nextRenewalDate sql.NullString) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getYearlySubscriptionsRenewingInMonth, nextRenewalDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.BillingCycle,
			&i.NextRenewalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlySubscriptions = `-- name: ListMonthlySubscriptions :many
SELECT id, name, amount, currency, billing_cycle, next_renewal_date, created_at, updated_at FROM subscriptions WHERE billing_cycle = 'monthly' ORDER BY name ASC
`

func (q *Queries) ListMonthlySubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listMonthlySubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.BillingCycle,
			&i.NextRenewalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, name, amount, currency, billing_cycle, next_renewal_date, created_at, updated_at FROM subscriptions ORDER BY name ASC
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.BillingCycle,
			&i.NextRenewalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByBillingCycle = `-- name: ListSubscriptionsByBillingCycle :many
SELECT id, name, amount, currency, billing_cycle, next_renewal_date, created_at, updated_at FROM subscriptions WHERE billing_cycle = ? ORDER BY name ASC
`

func (q *Queries) ListSubscriptionsByBillingCycle(ctx context.Context, billingCycle string) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByBillingCycle, billingCycle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.BillingCycle,
			&i.NextRenewalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYearlySubscriptions = `-- name: ListYearlySubscriptions :many
SELECT id, name, amount, currency, billing_cycle, next_renewal_date, created_at, updated_at FROM subscriptions WHERE billing_cycle = 'yearly' ORDER BY next_renewal_date ASC
`

func (q *Queries) ListYearlySubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listYearlySubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.BillingCycle,
			&i.NextRenewalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConfig = `-- name: SetConfig :exec
INSERT INTO config (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetConfigParams struct {
	Key   string
	Value string
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConfig, arg.Key, arg.Value)
	return err
}

const updateRenewalDate = `-- name: UpdateRenewalDate :one
UPDATE subscriptions
SET next_renewal_date = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, amount, currency, billing_cycle, next_renewal_date, created_at, updated_at
`

type UpdateRenewalDateParams struct {
	NextRenewalDate sql.NullString
	ID              int64
}

func (q *Queries) UpdateRenewalDate(ctx context.Context, arg UpdateRenewalDateParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, updateRenewalDate, arg.NextRenewalDate, arg.ID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.BillingCycle,
		&i.NextRenewalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET name = ?, amount = ?, currency = ?, billing_cycle = ?, next_renewal_date = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, amount, currency, billing_cycle, next_renewal_date, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	Name            string
	Amount          float64
	Currency        string
	BillingCycle    string
	NextRenewalDate sql.NullString
	ID              int64
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, updateSubscription,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.BillingCycle,
		arg.NextRenewalDate,
		arg.ID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.BillingCycle,
		&i.NextRenewalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
